### ISSUE TITLE
MacOS test on a real machine

### ISSUE THREAD

**Issue by fibodevy** [webui-dev/pascal-webui#11]
Since I dont have any Mac, Im asking for help to check if Pascal WebUI wrapper is working fine there, in real world. I only tested on VirtualBox.

Branch with MacOS support:

https://github.com/webui-dev/pascal-webui/tree/MacOS

I suggest to check if `text editor` example from `examples/Lazarus` directory works. Install `Lazarus`, open `text_editor.lpi`, compile, run. `webui-2.dylib` is required and it has to be in the same folder where the compiled executable is.

Any Mac owner can test. WebUI binaries for MacOS are available here: [v2.4.0](https://github.com/webui-dev/webui/releases/tag/2.4.0).

<hr>

## Lazarus installation with `fpcupdeluxe`

Download the tool (I used `fpcupdeluxe-x86_64-darwin-cocoa.zip`):
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.4.0a

Open, click `Trunk` in the left bottom corner, it will install latest Lazarus + FPC, thats all you need.

<hr>

![eLFobEZ0f5](https://github.com/webui-dev/pascal-webui/assets/21068718/fa6fa5af-7c93-4ec2-976d-e4225ef3801e)

**Comment by mijn-design** [comment]
I could give it a try with a Macbook M1 Pro, may take a few days. Need to install Lazarus (my business is Delphi).

**Comment by hassandraga** [comment]
> my business is Delphi

https://github.com/salvadordf/WebUI4Delphi
