### ISSUE TITLE
Delphi not working

### ISSUE THREAD

**Issue by mijn-design** [webui-dev/pascal-webui#12]
I adapted webui.pas for Delphi, generated the JS file and and compiled a console project without error or warning.
Nevertheless nothing happened when running the program - in an Paralles VM with Windows 11 ARM on a Macbook M1 Pro.
Tried same on a PC again nothing happened. 

Have no idea where to start searching for the problem. 
Maybe you can give me a hint?

**Comment by delphius** [comment]
> Maybe you can give me a hint?

you can upload your project that does not work on github or attach it here as an archive, guessing on coffee grounds is unlikely to work, and all telepaths are on vacation))))

**Comment by AlbertShown** [comment]
I don't know what you mean by generated JS, but I should let you know that `webui.js` gets generated on runtimes, so, copying it and embedding it into your project won't work. You need to use `<script src="/webui.js"></script>`.

**Comment by AlbertShown** [comment]
On the other hand, you can share the webui logs to know what is going on quickly.

1. Download the [webui 2.4.0 release](https://github.com/webui-dev/webui/releases/) archive
2. Extract it, and copy the `/debug/webui-2.dll` file to your Delphi project
3. Run your Delphi app again, and this time, you will see the whole webui logs in terminal

**Comment by fibodevy** [comment]
Please provide an example of a Delphi project that is not working. Until then, I'm closing this issue.
