### ISSUE TITLE
Can you modify it and support delphi?

### ISSUE THREAD

**Issue by dqi1999** [webui-dev/pascal-webui#13]
Can you modify it and support delphi?

**Comment by fibodevy** [comment]
What is the current problem if you try to compile it with Delphi? What are the error messages?

You can also try to use this test branch which has `{$mode Delphi}` switch:
https://github.com/webui-dev/pascal-webui/blob/MacOS/src/webui.pas

**Comment by hassandraga** [comment]
https://github.com/salvadordf/WebUI4Delphi
