### ISSUE TITLE
Text Editor Example not working under Linux -> index.html not found

### ISSUE THREAD

**Issue by reckel-jm** [webui-dev/pascal-webui#15]
Hello,

the editor example is not working under Arch Linux (Qt6). It seems that the file `index.html` can not be loaded.
![grafik](https://github.com/webui-dev/pascal-webui/assets/57252256/ccba8137-474e-4871-8bfb-fe0302098aea)

According to the section of the [webui documentation](https://webui.me/docs/2.5/#/?id=backend-set_root_folder), the **absolute path** is necessary for `webui_set_root_folder`, so I tried that as well. But I get the same result.

If I change lines 23-25 to

```pascal
// Show the window, preferably in a Chromium based browser
if not webui_show_browser(window, 'ui/index.html', WEBUI_Chromium) then
  webui_show(window, 'ui/index.html');      
```

Then, the page will be loaded, but apparently not its CSS and JS files.
![grafik](https://github.com/webui-dev/pascal-webui/assets/57252256/e6577f9a-19c3-4a4b-b2a9-4f764d2dc587)

**Comment by hassandraga** [comment]
I believe that this issue is fixed in the recent webui C commits, the Pascal wrapper needs to be updated.
Thank you @reckel-jm for the report.

**Comment by reckel-jm** [comment]
Thank you for answering! @hassandraga 

I'll leave this issue open till the Pascal Wrapper has been updated.

**Comment by hassandraga** [comment]
Sure, but meanwhile, you can try to download and replace the WebUI dynamic library manually.
https://github.com/webui-dev/webui/releases/tag/2.5.0-beta.2

**Comment by reckel-jm** [comment]
Hallo @hassandraga,

I have tested the newer library and I can confirm that now everything is working fine.
The problem seems to be solved so far.

Thank you for the effort in this project!
