### ISSUE TITLE
webui_interface_set_response

### ISSUE THREAD

**Issue by AlbertShown** [webui-dev/pascal-webui#2]
In the this [example](https://github.com/webui-dev/pascal-webui/blob/main/examples/qxexample/qxexample.pas), we used `webui_interface_set_response()`, I guess we should use instead `webui_return_string()`.

The function `webui_interface_set_response()` works fine, but all functions starting with `webui_interface_xxx` are designed to be used by the wrappers, like [Pascal-Wraper](https://github.com/webui-dev/pascal-webui/blob/main/src/webui.pas).

The best solution is to make the examples use 100% Pascal code style by doing this:

```
[Pascal Example] -> [webui.pas] -> [WebUILib]
[WebUILib] -> [webui.pas events listener] -> [Pascal Example Callback]
```

**Comment by delphius** [comment]
Changed the example in accordance with the recommendations
