### ISSUE TITLE
type no defined

### ISSUE THREAD

**Issue by NouziMoggar** [webui-dev/pascal-webui#9]
lazarus and free pascal trunk

...
webui.pas(52,12) Error: Identifier not found "ULONG_PTR"
webui.pas(52,21) Error: Error in type definition
webui.pas(58,13) Error: Illegal expression
webui.pas(59,17) Error: Illegal expression
webui.pas(61,19) Error: Illegal expression
webui.pas(62,14) Error: Illegal expression
webui.pas(68,60) Error: Type "size_t" is not completely defined
.....
webui.pas(162,48) Verbose: There were 50 errors compiling module, stopping
Verbose: Compilation aborted
Verbose: /home/nouzi/dev/trunk/fpc/bin/x86_64-linux/ppcx64 returned an error exitcode

**Comment by fibodevy** [comment]
Thank you for reporting this.

If you change line 52 to
```pas
size_t = SizeUInt;
```

Or

```pas
size_t = PtrUInt;
```

Does it work?

**Comment by fibodevy** [comment]
Anyway, its fixed now, but still letting me know if you have `SizeUInt` and `PtrUInt` defined in your FPC will help

**Comment by NouziMoggar** [comment]
I go to try

**Comment by delphi17** [comment]
Other err

Hint: (11030) Start of reading config file /home/nouzi/dev/trunk/fpc/bin/x86_64-linux/fpc.cfg
Hint: (11031) End of reading config file /home/nouzi/dev/trunk/fpc/bin/x86_64-linux/fpc.cfg
Free Pascal Compiler version 3.3.1-14233-g376de92a50 [2023/10/25] for x86_64
Copyright (c) 1993-2023 by Florian Klaempfl and others
(1002) Target OS: Linux for x86-64
(3104) Compiling minimal.lpr
(3104) Compiling /home/nouzi/dev/componetplus/pascal-webui-main/src/webui.pas
(9015) Linking /home/nouzi/dev/test/web/webui/minimal
/usr/bin/ld.bfd: cannot find -lwebui-2: No such file or directory
/home/nouzi/dev/test/web/webui/minimal.lpr(15,1) Error: (9013) Error while linking
/home/nouzi/dev/test/web/webui/minimal.lpr(15,1) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /home/nouzi/dev/trunk/fpc/bin/x86_64-linux/ppcx64 returned an error exitcode

**Comment by NouziMoggar** [comment]
Other err
my system linux x86_64
if Target OS =  winx86-64   compile success 
else  Target OS = linux86-64  
.....
(1002) Target OS: Linux for x86-64
(3104) Compiling text_editor.lpr
/home/nouzi/dev/componetplus/pascal-webui-main/examples/Lazarus/text editor/text_editor.lpr(7,20) Hint: (5024) Parameter "e" not used
/home/nouzi/dev/componetplus/pascal-webui-main/examples/Lazarus/text editor/text_editor.lpr(12,16) Hint: (5024) Parameter "e" not used
/home/nouzi/dev/componetplus/pascal-webui-main/examples/Lazarus/text editor/text_editor.lpr(7,11) Hint: (5028) Local proc "btnclose" is not used
/home/nouzi/dev/componetplus/pascal-webui-main/examples/Lazarus/text editor/text_editor.lpr(12,11) Hint: (5028) Local proc "save" is not used
/home/nouzi/dev/componetplus/pascal-webui-main/examples/Lazarus/text editor/text_editor.lpr(20,3) Note: (5025) Local variable "window" not used
/home/nouzi/dev/componetplus/pascal-webui-main/examples/Lazarus/text editor/text_editor.lpr(5,12) Hint: (5023) Unit "Dialogs" not used in text_editor
(9015) Linking /home/nouzi/dev/componetplus/pascal-webui-main/examples/Lazarus/text editor/text_editor
/usr/bin/ld.bfd: cannot find -lwebui-2: No such file or directory
/home/nouzi/dev/componetplus/pascal-webui-main/examples/Lazarus/text editor/text_editor.lpr(42,1) Error: (9013) Error while linking
/home/nouzi/dev/componetplus/pascal-webui-main/examples/Lazarus/text editor/text_editor.lpr(42,1) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /home/nouzi/dev/trunk/fpc/bin/x86_64-linux/ppcx64 returned an error exitcode


i Sorry for my English is bad

**Comment by fibodevy** [comment]
I will have to set up some Linux testing environement, that will take a while, currently Im working and testing on Windows.

The only error I see here is about the linking, `/usr/bin/ld.bfd: cannot find -lwebui-2: No such file or directory`

**Comment by delphius** [comment]
> The only error I see here is about the linking, `/usr/bin/ld.bfd: cannot find -lwebui-2: No such file or directory`

Linking by `ld` is about static linking, not dynamic using of dll/so, link option -l expected to find webui-2.a

**Comment by NouziMoggar** [comment]
Today I got an executable file
![image](https://github.com/webui-dev/pascal-webui/assets/11421086/486cc6fb-02b0-4655-887c-29f751bdf91b)

---- see this output
file ./text_editord
./text_editor: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, for GNU/Linux 2.4.0, stripped
--- end output


 the problem is that it does not work
![image](https://github.com/webui-dev/pascal-webui/assets/11421086/27325d17-ad40-4515-97c7-8b659b94e54e)

----  output
./text_editor
~/dev/componetplus/pascal-webui-main/examples/Lazarus/text editor$ 
--- end output

**Comment by NouziMoggar** [comment]
Past results with empty code, when adding the code some errors appear


https://github.com/webui-dev/pascal-webui/assets/11421086/3fbdf28a-82a6-4fb4-a371-cb905d93a128

**Comment by hassandraga** [comment]
According to the video, it seems that the LD does not find the `pthread`. Normally, using GCC/Clang in Linux, the WebUI app should be linked like this `-lpthread -lm -lwebui-2`. But `webui.pas` only use `-lwebui-2` (_webuilib = 'webui-2'+libext;_).

The solution is adding `pthread` and `m` library in `webui.pas` for Linux.

**Comment by NouziMoggar** [comment]
@hassandraga  
Can you explain how to add those libraries 

tnk

**Comment by hassandraga** [comment]
I can't test it right now. But you can give it a try, if it works you can create a PR to fix this issue.

Modify:

`  webuilib = 'webui-2'+libext;`

To

```
  webuilib = 'webui-2'+libext;
  {$ifdef UNIX} 
    {$linklib pthread}
    {$linklib m}
  {$endif}
```

**Comment by fibodevy** [comment]
Just updated the wrapper.

Can you check if it works for you now?

Please follow the instructions in [Text Editor README](https://github.com/webui-dev/pascal-webui/tree/main/examples/Lazarus/text%20editor)

**Comment by NouziMoggar** [comment]
Yes it works


![image](https://github.com/webui-dev/pascal-webui/assets/11421086/b012c621-327b-44b5-9036-b7cbe784b863)

Thanks fibodevy Thanks hassandraga

**Comment by fibodevy** [comment]
Thank you for confirming @delphi17
